=== vital-dhaveloose/aldb/api/activity.schema.json
{
    "id": "http://aldb.org/schema/ActivityVersion",
    "$schema": "http://json-schema.org/draft-04/schema",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "format": "uri",
            "description": "Schema meta field to reference this schema with."
        },
        "id": {
            "type": "string",
            "format": "uri",
            "description": "The identifier of the Activity, formatted as a URI."
        },
        "version": {
            "type": "string",
            "description": "A version representation of the ActivityVersion"
        },
        "label": {
            "type": "object",
            "description": "A map with short strings for representing the Activity in a UI. The keys of the map are locales.",
            "additionalProperties": {
              "type": "string"
            }
        },
        "period": {
            "$ref": "#/definitions/period",
            "description": "The period in which the Activity is considered 'current'."
        },
        "participations": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/participation"
            }
        },
        "subs": {
            "type": "array",
            "items": {
                "$ref": "#"
            },
            "description": "Activities that are part of this Activity."
        },
        "supers": {
            "type": "array",
            "items": {
                "$ref": "#"
            },
            "description": "Activities that this Activity is part of."
        },
        "attributeSets": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "manifest": {
                        "$ref": "#/definitions/attributeSetManifest"
                    },
                    "attributes": {
                        "type": "object"
                    }
                },
                "additionalProperties": false
            }
        },
        "blob": {
            "type": "object",
            "properties": {
                "manifest": {
                    "$ref": "#/definitions/blobManifest"
                },
                "bytesBase64": {
                    "type": "string"
                },
                "blobRef": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "additionalProperties": false
        }
    },
    "additionalProperties": false,
    "definitions": {
        "participation": {
            "type": "object",
            "properties": {
                "participator": {
                    "type": "object",
                    "anyOf": [
                        {
                            "$ref": "#/definitions/person"
                        },
                        {
                            "$ref": "#/definitions/group"
                        }
                    ]
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "uri"
                    },
                    "description": "An array of URIs referencing the roles of the participators in this participation."
                }
            }
        },
        "person": {
            "type": "object",
            "properties": {
                "givenName": {
                    "type": "string"
                },
                "familyName": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "format": "email"
                }
            }
        },
        "group": {
            "type": "object",
            "description": "A group of people.",
            "properties": {
                "display": {
                    "type": "string",
                    "description": "A string describing the Group, for example: \"Team Blue\""
                },
                "email": {
                    "type": "string",
                    "format": "email"
                }
            }
        },
        "period": {
            "type": "object",
            "properties": {
                "startTime": {
                    "type": "string",
                    "format": "date-time"
                },
                "endTime": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "additionalProperties": false
        },
        "attributeSetManifest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "format": "uri"
                }
            }
        },
        "blobManifest": {
            "type": "object",
            "properties": {
                "mediaType": {
                    "type": "string"
                }
            }
        }
    }
}

=== vital-dhaveloose/aldb/api/examples/activity-example-project.json
{
    "$schema": "https://raw.githubusercontent.com/vital-dhaveloose/aldb/main/api/activity.schema.json",
    "id": "http://uius.dhav.eu/activities/f6362685-b271-45a3-a92e-593f69e95b91",
    "version": "0",
    "label": {
        "en-GB": "Bathroom renovation",
        "icon": "ðŸ›€"
    },
    "period": {
        "startTime": "2020-05-15T00:00:00+01:00"
    },
    "participations": [
        {
            "participator": {
                "givenName": "Vital",
                "familyName": "D'haveloose",
                "email": "vital.dhaveloose@dhav.eu"
            },
            "roles": [
                "http://uius.org/apps/projects/roles/lead"
            ]
        }
    ],
    "subs": [
        {
            "id": "http://uius.dhav.eu/activities/529d999c-ffe7-473a-a3ac-e784f59e16fd",
            "label": {
                "en-GB": "Choosing tiles"
            },
            "attributeSets": {
                "http://uius.org/apps/tasks/schema#Task": {
                    "manifest": {
                        "id": "http://uius.org/apps/tasks/schema#Task"
                    },
                    "attributes": {
                        "status": "done"
                    }
                }
            },
            "subs": [
                {
                    "id": "http://uius.dhav.eu/activities/8919153c-387c-4cbf-8e25-e9789487eb93",
                    "label": {
                        "en-GB": "comparison table"
                    }
                }
            ]
        }
    ],
    "attributeSets": {
        "https://dhav.eu/schemas/project": {
            "manifest": {
                "id": "https://dhav.eu/schemas/project"
            },
            "attributes": {
                "priority": "normal",
                "deadline": "2020-07-16"
            }
        }
    },
    "blob": {
        "manifest": {
            "media-type": "text/markdown"
        },
        "bytesBase64": "IyBJZGVhcwotIG1hbnkgdHJvcGljIHBsYW50cwotIGdyZWVuIHZlcnRpY2FsIHRpbGVzCi0gcmVjdXBlcmF0ZSBoZWF0IG9mIHNob3dlciBkcmFpbmFnZQ=="
    }
}

=== vital-dhaveloose/aldb/api/examples/activity-example-calendar.json
{
    "$schema": "https://raw.githubusercontent.com/vital-dhaveloose/aldb/main/api/activity.schema.json",
    "id": "http://uius.dhav.eu/activities/f6362685-b271-45a3-a92e-593f69e95b91",
    "version": "0",
    "label": {
        "en-GB": "Hairdresser appointment",
        "icon": "✂️"
    },
    "period": {
        "startTime": "2020-01-15T15:30:00Z",
        "endTime": "2020-01-15T16:00:00Z"
    },
    "participations": [
        {
            "participator": {
                "givenName": "Vital",
                "familyName": "D'haveloose",
                "email": "vital.dhaveloose@dhav.eu"
            },
            "roles": [
                "http://uius.org/apps/calendar/roles/organiser"
            ]
        }
    ],
    "attributeSets": {
        "http://uius.org/apps/calendar/schema#Event": {
            "manifest": {
                "id": "http://uius.org/apps/calendar/schema#Event",
                "attributes": {
                    "priority": "normal",
                    "reminder": "2020-01-15T15:00:00Z",
                    "location": {
                        "display": "Hair Salon X"
                    }
                }
            }
        }
    }
}
